[package]
name = "sentinel"
version = "0.2.0"
edition = "2021"
authors = ["Nils Mathieu <nils.mathieu.contact@gmail.com>"]

[features]
default = ["null"]

null = ["memchr"]
nightly = []

[dependencies]
memchr = { version = "2", optional = true }
