[package]
name = "sentinel"
version = "0.0.1"
edition = "2021"
authors = ["Nils Mathieu <nils.mathieu.contact@gmail.com>"]

[features]
default = ["default_impl", "cstr"]

# Adds the `Default` type, which implements the `Sentinel` trait for every common type.
default_impl = ["memchr"]

# Adds the `CStr` type.
cstr = ["default_impl"]

[dependencies]
memchr = { version = "2", optional = true }
