[package]
name = "sentinel"
version = "0.2.0"
edition = "2021"
authors = ["Nils Mathieu <nils.mathieu.contact@gmail.com>"]

[features]
default = ["null"]

# Adds the `Null` type, which implements the `Sentinel` trait for every common type.
null = ["memchr"]

[dependencies]
memchr = { version = "2", optional = true }
